// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwDEUojfJDvhUp1Tv_6Quc0Oz4QSQpt4c',
    appId: '1:864619252619:web:5dee393e8c5b87b41a7d8e',
    messagingSenderId: '864619252619',
    projectId: 'smarthome-58ae1',
    authDomain: 'smarthome-58ae1.firebaseapp.com',
    storageBucket: 'smarthome-58ae1.appspot.com',
    measurementId: 'G-PSXD0P95X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzJfoKQI7tcuDu6rvum8dWlfkcDbU7MZk',
    appId: '1:864619252619:android:6f35a6276f385a8c1a7d8e',
    messagingSenderId: '864619252619',
    projectId: 'smarthome-58ae1',
    storageBucket: 'smarthome-58ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNyJJq64okzavWTUjRq7Sq_IAEhcI7M0k',
    appId: '1:864619252619:ios:e8447117223a1db91a7d8e',
    messagingSenderId: '864619252619',
    projectId: 'smarthome-58ae1',
    storageBucket: 'smarthome-58ae1.appspot.com',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNyJJq64okzavWTUjRq7Sq_IAEhcI7M0k',
    appId: '1:864619252619:ios:cd9e205405bc79ac1a7d8e',
    messagingSenderId: '864619252619',
    projectId: 'smarthome-58ae1',
    storageBucket: 'smarthome-58ae1.appspot.com',
    iosBundleId: 'com.example.smartHomeApp.RunnerTests',
  );
}
